---
version: "3.8"
services:
  web:
    build:
      context: .
    working_dir: /app/
    command: /bin/sh -c "npm install && npm run dev"
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
