version: "3.8"
services:
  web:
    build:
      context: ./  
    command: /bin/sh -c "npm install && npm run dev"
    volumes:
      - .:/app/
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
