version: '3.8'
services:
  web:
    build:
      context: ./
      target: dev
    volumes:
      - ./src:/src
    command: npm run dev
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development