#!/usr/bin/env bash

set -e
systemctl daemon-reload
systemctl enable --now imls-update.timer

# set hostname
DEVICE_TAG=$(sqlite3 /opt/imls/config.sqlite 'select device_tag from ConfigDBs')
FCFS_SEQ_ID=$(sqlite3 /opt/imls/config.sqlite 'select fcfs_seq_id from ConfigDBs')
if [[ ! -z "${DEVICE_TAG}" && ! -z "${FCFS_SEQ_ID}" ]]
then
    hostnamectl set-hostname "${FCFS_SEQ_ID}-${DEVICE_TAG}.local"
    systemctl restart avahi-daemon
fi

# nginx
systemctl enable nginx.service
mkdir -p /www/imls
chown -R www-data:www-data /www*
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/session-counter.conf /etc/nginx/sites-enabled/
systemctl restart nginx.service

systemctl restart session-counter
