monitoring:
  pinginterval: 10
  max_http_error_count: 10
  http_error_interval_mins: 60
  # How long we maintain a MAC -> UID mapping.
  # If we don't see a device for this many minutes, then
  # we drop the mapping. If the device shows up again, it will
  # be a "new" device.
  uniqueness_window: 120
  # rounds is the number of listening rounds we do before
  # reporting up to the server. 
  rounds: 3
  # threshold is how many rounds a MAC address must be present
  # before we consider reporting it to the server.
  threshold: 2
  # EXAMPLE:
  # rounds of 10 and threshold of 8 would have a 10m reporting window
  # and require a device to be present 8 out of 10 minutes.
  # rounds of 60 and threshold of 30 would watch for an hour, and then 
  # consider any device that was present for 30 minutes to be 

# These are two different endpoints.
# They will both go through umbrella...
# So only the path should be
umbrella:
  scheme: https
  host: api.data.gov
  data: /TEST/10x-imls/ # reporting what would have been pls_data
  logging: /TEST/10x-imls-2/items/pls_events # pls_events
wireshark:
  path: /usr/bin/tshark
  adapter: wlan1
  # duration is the number of seconds that wireshark
  # will listen to the adapter before reporting out.
  # best if this is below one minute.
  # FIXME: this should not be configurable.
  duration: 45
manufacturers:
  db: /etc/session-counter/manufacturers.sqlite
