---
- hosts: localhost
  connection: local
  collections:
    - devsec.hardening
  roles:
    - packages
    - unattended-upgrades
    - session-counter
    - configure-monitor-mode
    - input-initial-configuration
  tasks:
    - name: run hardening as root
      include_role:
        - devsec.hardening.os_hardening
      become: yes
    - name: lockdown conditionally
      include_role:
        name: lockdown
      when: "lockdown"
