---
- hosts: localhost
  connection: local
  collections:
    - devsec.hardening
  roles:
    - packages
    - unattended-upgrades
    - session-counter
    - configure-monitor-mode
    - input-initial-configuration
    - { role: devsec.hardening.os_hardening, become: yes }
  tasks:
    - name: lockdown conditionally
      include_role:
        name: lockdown
      when: "lockdown"
