FROM postgres:15.0-bullseye

RUN apt-get update && apt-get install -y \
    build-essential \
    git \
    postgresql-contrib-14 \
    postgresql-server-dev-14    
WORKDIR /pgjwt
RUN git clone https://github.com/michelp/pgjwt
RUN cd pgjwt && make install
