#!/usr/bin/env bash

set -e
systemctl enable nginx.service
mkdir -p /www/imls
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/session-counter.conf /etc/nginx/sites-enabled/
systemctl restart nginx.service
