---
name: User Story
description: Use this form to create a new user story
labels: ["story"]
body:
  - type: markdown
    attributes:
      value: |
        This form will guide you through creating a new [user story](https://www.agilealliance.org/glossary/user-stories/).
  - type: input
    id: persona
    attributes:
      label: User / Persona
      description: 'A user story is viewed from the perspective of a user or persona, such "survey administrator" or "software engineer"'
      placeholder: '(who) As a...'
    validations:
      required: true
  - type: input
    id: request
    attributes:
      label: Request
      description: 'Next, a user story includes the request; note: here we share what we want, not how we want it done'
      placeholder: '(what) I want...'
    validations:
      required: true
  - type: input
    id: reason
    attributes:
      label: Reason / Justification
      description: 'Finally, a user story involves a reason or a justification as to why the story should be completed -- an answer to "why should we do this?"'
      placeholder: '(why) so that....'
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Optional fields
  - type: textarea
    id: dod
    attributes:
      label: Definition of Done (DoD)
      description: The Definition of Done is a list of criteria under which the team would consider this story complete; may include references to issues
      value: "- [ ] "
      render: markdown
    validations:
      required: false
  - type: textarea
    id: ac
    attributes:
      label: Acceptance Criteria (AC)
      description: The Acceptance Criteria is a series of tests meant to confirm that things are working as-expected
      value: "- [ ] "
      render: markdown
    validations:
      required: false
  - type: textarea
    id: other
    attributes:
      label: Other Notes
      description: List any additional notes (e.g., resources, links, diagrams, etc.) that the team may find useful or helpful when working on this user story.
      render: markdown
    validations:
      required: false
