# This role hardens the pi.
- name: make sure ufw is installed
  ansible.builtin.package:
    name: ufw
    state: present
  become: yes

# This is it. Once this runs, nothing gets in.
- name: block all incoming traffic
  ansible.builtin.command:
    cmd: ufw default deny incoming
  become: yes

- name: disable logging; we'll never see it
  ansible.builtin.command:
    cmd: ufw logging off
  become: yes

- name: explicitly disable ssh daemon
  service:
    name: ssh
    enabled: no
    state: stopped
  when: preserve_ssh is undefined
  become: yes

- name: Disable root login
  user:
    name: root
    password_lock: true
  when: preserve_users is undefined
  become: yes

- name: Disable pi login
  user:
    name: pi
    password_lock: true
  when: preserve_users is undefined
  become: yes

# FIXME: This needs to be removed when testing is complete.
- name: allow SSH when lockdown is not enabled
  ansible.builtin.command:
    cmd: ufw allow OpenSSH
  become: yes
  when: preserve_ssh is defined

# https://raspberrypi.stackexchange.com/questions/109422/how-to-disable-logs
- name: stop rsyslog
  ansible.builtin.command:
    cmd: systemctl stop rsyslog
  become: yes

- name: disable rsyslog
  ansible.builtin.command:
    cmd: systemctl disable rsyslog
  become: yes

- name: limit journald
  ansible.builtin.lineinfile:
    path: /etc/systemd/journald.conf
    state: present
    line: "{{ item }}"
    create: true
  become: yes
  loop:
    - "Storage=volatile"
    - "RuntimeMaxUse=64M"
    - "SystemMaxUse=0M"