#!/usr/bin/env bash

set -e

# lock down user accounts.
usermod -L pi
usermod -L root
usermod -s /sbin/nologin pi
usermod -s /sbin/nologin root
chage -E0 pi
chage -E0 root

# stop services.
systemctl disable rsyslog
systemctl stop rsyslog
systemctl disable ssh

# limit journald.
cat <<EOF >> /etc/systemd/journald.conf
Storage=volatile
RuntimeMaxUse=64M
SystemMaxUse=0M
EOF

# firewall.
ufw logging off
ufw default deny incoming

# reboot in one minute.
systemctl daemon-reload
systemctl start reboot-1m.timer
