# This role hardens the pi.
- name: make sure ufw is installed
  ansible.builtin.package:
    name: ufw
    state: present
  become: yes

# This is it. Once this runs, nothing gets in.
- name: block all incoming traffic
  ansible.builtin.command:
    cmd: ufw default deny incoming
  become: yes

- name: disable logging; we'll never see it
  ansible.builtin.command:
    cmd: ufw logging off
  become: yes

- name: explicitly disable ssh daemon
  service:
    name: ssh
    enabled: no
    state: stopped
  when: preserve_ssh is undefined

- name: Disable root login
  user:
    name: root
    password_lock: true
  when: preserve_users is undefined

- name: Disable pi login
  user:
    name: pi
    password_lock: true
  when: preserve_users is undefined

# FIXME: This needs to be removed when testing is complete.
- name: allow SSH when lockdown is not enabled
  ansible.builtin.command:
    cmd: ufw allow OpenSSH
  become: yes
  when: preserve_ssh is defined
