name: Linux ARM build

on:
  push:
    paths:
      - 'imls-wifi-sensor/**'
      - '.github/workflows/automate_arm_linux_build.yml'
  pull_request:
    paths:
      - 'imls-wifi-sensor/**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          # The Go version to download (if necessary) and use.
          #go-version: '1.19.5'
          go-version-file: imls-wifi-sensor/go.mod
          cache-dependency-path: imls-wifi-sensor/go.sum
      - name: build the executables
        run: | 
          cd imls-wifi-sensor
          make -f Makefile.gh-actions all
          ls 
          echo "This is the GITHUB_WORKSPACE variable: $GITHUB_WORKSPACE"
          ls $GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE/imls-wifi-sensor
      - name: Upload the artifacts
        uses: actions/upload-artifact@v3
        with:
          name: session-counter
          path: imls-wifi-sensor/session-counter
          #wifi-hardware-search-cli
