name: Backend CI
run-name: Pytest check on imls-backend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    defaults:
      run:
        working-directory: imls-backend
    runs-on: ubuntu-latest

    steps:
        - name: Build the Docker image and run pytest
          uses: actions/checkout@v3
        - run: echo "PGRST_JWT_SECRET='github-action-secret'" > .env
        - run: echo "POSTGRES_USER='postgres'" >> .env
        - run: echo "POSTGRES_PASSWORD='imlsimlsimls'" >> .env
        - run: echo "POSTGRES_USER='postgres'" >> .env
        - run: echo "POSTGRES_DB='imls'" >> .env
        - run: echo "DATABASE_URL='postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@localhost:5432/${POSTGRES_DB}?sslmode=disable'" >> .env
        - run: docker build -t imls/postgres:latest -f Dockerfile.pgjwt . && docker compose up -d
        - run: docker exec -it postgres_db mkdir /test
        - run: docker copy .env postgres_db:.env
        - run: docker copy test/setup-for-tests.sh
        - run: docker exec -it /bin/bash test/setup-for-tests.sh
        - name: Run poetry and run Pytest
          uses: Gr1N/setup-poetry@v8
        - run: /bin/bash test/setup-for-tests.sh
        - run: poetry install
        - run: poetry shell
        - run: source test/.test_config && pytest test/

