name: Backend CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:
    defaults:
      run:
        working-directory: imls-backend
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: Gr1N/setup-poetry@v8
    - name: Build the Docker image and run pytest
    - run: docker build -t imls/postgres:latest -f Dockerfile.pgjwt .
    - run: docker compose up -d
    - run: /bin/bash test/setup-for-tests.sh
    - run: poetry install
    - run: poetry shell
    - run: source test/.test_config && pytest test/

